<a href="https://colab.research.google.com/github/maya-nakamura/opendata/blob/main/geotiff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Geotiff（ラスターデータ）を読む

### 資料
コードの参考：https://qiita.com/HidKamiya/items/d5e69fda61703abe1a58<br>
https://gis-oer.github.io/gitbook/book/materials/python/07/07.html <br>
データサイト：https://e4ftl01.cr.usgs.gov/MEASURES/GFSAD30SEACE.001/2013.01.01/

### 作業領域を指定する

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# ディレクトリパス
current_directory = "/content/drive/MyDrive/seminar2022/卒業研究/nakamura/2022figure/Others/"

In [ ]:
# 作業ディレクトリを移動する
%cd /content/drive/MyDrive/seminar2022/卒業研究/nakamura/2022figure/Others/

/content/drive/MyDrive/seminar2022/卒業研究/nakamura/2022figure/Others


In [ ]:
# 必要なモジュールをインポートする
import numpy as np
from osgeo import gdal, gdalconst, gdal_array   # gdal は画像を読み込むためのアプリ
from osgeo import osr # 空間参照モジュール
import csv

### データを読み込む

In [ ]:
# データを読み込む
file = current_directory + 'data/' +  "GFSAD30SEACE_2015_N00E100_001_2018080123000.tif"
src = gdal.Open(file, gdalconst.GA_ReadOnly) # tifの読み込み (read only)
type(src)   # クラス

osgeo.gdal.Dataset

In [ ]:
src.RasterXSize # 横方向数

37114

In [ ]:
src.RasterYSize # 縦方向数

37253

In [ ]:
src.RasterCount # バンド数

1

In [ ]:
b1 = src.GetRasterBand(1).ReadAsArray() # 第１バンド numpy array
print(b1)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 1 2 2]
 [1 1 1 ... 2 2 2]
 [1 1 1 ... 2 2 1]]


In [ ]:
width = b1.shape[1]
print(width)
height = b1.shape[0]
print(height)

37114
37253


実行に11分、ファイルサイズ2.75G

In [ ]:
# csvファイルに吐いてみる
with open(current_directory + 'out/' + 'geotiff_test.csv','w') as f:
    writer = csv.writer(f)
    for i in range(width):
        writer.writerow(b1[i])

In [ ]:
print(b1[0][0])

0


In [ ]:
print(sum(b1[0]))

11124


実行時間4分

In [ ]:
# 緯度ごとに積算する
sum_list = []
for i in range(width):
    sum_list.append(sum(b1[i]))
print(sum_list)

[11124, 11140, 11181, 11170, 11166, 11200, 11194, 11196, 11238, 11242, 11278, 11286, 11303, 11256, 11228, 11209, 11202, 11182, 11150, 11110, 11073, 11071, 11033, 11005, 10986, 10985, 10970, 10940, 10946, 10939, 10926, 10892, 10874, 10913, 10898, 10911, 10880, 10891, 10889, 10868, 10817, 10809, 10811, 10800, 10830, 10823, 10829, 10805, 10789, 10780, 10748, 10719, 10668, 10637, 10644, 10578, 10567, 10553, 10558, 10577, 10585, 10529, 10521, 10538, 10530, 10481, 10523, 10507, 10488, 10498, 10501, 10514, 10508, 10480, 10496, 10550, 10596, 10631, 10629, 10645, 10632, 10585, 10584, 10586, 10589, 10600, 10533, 10505, 10512, 10519, 10512, 10533, 10504, 10485, 10496, 10495, 10434, 10394, 10394, 10403, 10430, 10458, 10485, 10481, 10491, 10479, 10425, 10404, 10362, 10371, 10380, 10360, 10333, 10327, 10350, 10361, 10376, 10314, 10292, 10275, 10252, 10238, 10284, 10265, 10244, 10210, 10210, 10137, 10161, 10175, 10230, 10219, 10189, 10209, 10200, 10185, 10200, 10227, 10231, 10233, 10246, 10229, 10224

In [ ]:
b1_dimention = b1.ndim  # データの次元数
print(b1_dimention)

2


In [ ]:
b1_size = b1.size
print(b1_size)

1382607842


In [ ]:
src.GetRasterBand(1).GetMetadata

<bound method MajorObject.GetMetadata of <osgeo.gdal.Band; proxy of <Swig Object of type 'GDALRasterBandShadow *' at 0x7efc71608990> >>

### 基礎情報の取得

In [ ]:
src.GetDescription() # ファイル名

'/content/drive/MyDrive/seminar2022/卒業研究/nakamura/2022figure/Others/data/GFSAD30SEACE_2015_N00E100_001_2018080123000.tif'

In [ ]:
src.GetProjection() # 座標系情報

'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]]'

### 画像メタデータの取得

In [ ]:
src.GetMetadata() # 辞書型のメタデータ配列

{'AREA_OR_POINT': 'Area'}

In [ ]:
src.GetMetadataItem('AREA_OR_POINT') # 項目指定

'Area'

### 画像の出力

各種座標値：（左上端のX座標, ピクセル幅, 回転角, 左上端のY座標, 回転角, ピクセル高さ）

In [ ]:
geotransform = src.GetGeoTransform()
print(geotransform)

(99.99893029220213, 0.00026949458523585647, 0.0, 10.038403805450418, 0.0, -0.00026949458523585647)


In [ ]:
originY = geotransform[3]
originX = geotransform[0]
pixelWidth = geotransform[1]
pixelHeight = geotransform[5]

In [ ]:
dst = current_directory + 'out/' +"test_image.tif"
driver = gdal.GetDriverByName('GTiff')
dst_raster = driver.Create(dst, width, height, 1, gdal.GDT_UInt16)

In [ ]:
dst_raster.SetGeoTransform((originX, pixelWidth, 0, originY, 0, pixelHeight))

0

In [ ]:
dst_band = dst_raster.GetRasterBand(1)
dst_band.WriteArray(b1)

0

In [ ]:
dst_band.FlushCache()
dst_raster = None

### 別データ

In [ ]:
# データを読み込む
file = current_directory + 'data/' +  "GFSAD1KCD.2010.001.2016348142525.tif"
src = gdal.Open(file, gdalconst.GA_ReadOnly) # tifの読み込み (read only)
type(src)   # クラス

osgeo.gdal.Dataset

In [ ]:
src.RasterXSize # 水平方向数

40430

In [ ]:
src.RasterYSize # 鉛直方向数

20160

In [ ]:
src.RasterCount # バンド数

1

In [ ]:
b1 = src.GetRasterBand(1).ReadAsArray() # 第１バンド numpy array
print(b1)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
width = b1.shape[1]
print(width)
height = b1.shape[0]
print(height)

40430
20160


In [ ]:
# 緯度ごとに土地利用をカウントする
count_list = []
for i in range(height):
    band_list = []
    band_list = b1[i].tolist()  # tolist()：NumPy配列ndarrayをリストに変換
    count_list.append(band_list.count(2))
print(count_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
b1_dimention = b1.ndim  # データの次元数
print(b1_dimention)

2


In [ ]:
b1_size = b1.size
print(b1_size)

815068800


各種座標値：（左上端のX座標, ピクセル幅, 回転角, 左上端のY座標, 回転角, ピクセル高さ）

In [ ]:
geotransform = src.GetGeoTransform()
print(geotransform)

(-180.01636766952797, 0.008928197055985389, 0.0, 90.00542337852794, 0.0, -0.008928197055985389)
